name: "ShellCheck"

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
        - name: ShellCheck
          uses: ludeeus/action-shellcheck@2.0.0
          with:
             scandir: 'build_debian_iso/srv_fai_config/scripts/SEAPATH'
